import type { Level, Dialogue, Player, InventoryItem } from './game-types'

// Initial player state
export const initialPlayer: Player = {
  position: { x: 100, y: 200 },
  width: 24,
  height: 32,
  speed: 2.5,
  direction: 'down',
  isMoving: false,
  health: 100,
  tapes: 0,
  sanity: 100,
  inventory: [],
  isHiding: false,
  isSprinting: false,
  stamina: 100,
  hasFlashlight: true,
  flashlightBroken: true, // Starts broken in level 1
}

// All game dialogues
export const dialogues: Record<string, Dialogue> = {
  // Level 1 - El Apartamento
  'intro_1': {
    id: 'intro_1',
    speaker: 'Narrador',
    text: 'Una noche como cualquier otra... o eso creía Adrián.',
    nextDialogueId: 'intro_2',
  },
  'intro_2': {
    id: 'intro_2',
    speaker: 'Narrador',
    text: 'Una caja misteriosa espera frente a su puerta. Dentro, una cinta VHS envuelta con una delgada cinta roja.',
    nextDialogueId: 'intro_3',
  },
  'intro_3': {
    id: 'intro_3',
    speaker: 'Adrián',
    text: '¿Qué es esto? No recuerdo haber pedido nada...',
    nextDialogueId: 'intro_4',
  },
  'intro_4': {
    id: 'intro_4',
    speaker: 'Sistema',
    text: '[OBJETIVO: Encuentra la cinta VHS. La electricidad falló - busca los 3 fusibles para restaurar la luz y abrir la puerta electrónica.]',
  },
  'fuse_1_found': {
    id: 'fuse_1_found',
    speaker: 'Adrián',
    text: 'Un fusible... Debe haber más. Sin luz no podré ver la cinta.',
    effect: 'give_item',
    effectData: 'fuse_1',
  },
  'fuse_2_found': {
    id: 'fuse_2_found',
    speaker: 'Adrián',
    text: 'Otro fusible. Uno más...',
    effect: 'give_item',
    effectData: 'fuse_2',
  },
  'fuse_3_found': {
    id: 'fuse_3_found',
    speaker: 'Adrián',
    text: '¡El último! Ahora debo encontrar la caja de fusibles.',
    effect: 'give_item',
    effectData: 'fuse_3',
  },
  'fusebox_hint': {
    id: 'fusebox_hint',
    speaker: 'Adrián',
    text: 'La caja de fusibles... Necesito insertar los 3 fusibles en el orden correcto. Vi unos números en los fusibles: 2, 1, 3.',
  },
  'fusebox_incomplete': {
    id: 'fusebox_incomplete',
    speaker: 'Adrián',
    text: 'La caja sigue muerta. Primero necesito reunir los 3 fusibles.',
  },
  'lights_restored': {
    id: 'lights_restored',
    speaker: 'Adrián',
    text: 'La electricidad vuelve. Las paredes falsas se desvanecen y el apartamento recupera su forma normal.',
  },
  'tape_1': {
    id: 'tape_1',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] La cinta muestra a una mujer caminando sola por una calle. La hora marcada... ¡aún no ha llegado!',
    effect: 'add_tape',
  },
  'complete_1': {
    id: 'complete_1',
    speaker: 'Adrián',
    text: 'Tengo que salir. Si esto es real... puedo evitar que algo terrible suceda.',
  },
  'buff_stamina': {
    id: 'buff_stamina',
    speaker: 'Sistema',
    text: '[POTENCIADOR] Respiración controlada: recuperas stamina para seguir avanzando.',
  },
  'buff_health': {
    id: 'buff_health',
    speaker: 'Sistema',
    text: '[POTENCIADOR] Vendaje improvisado: recuperas salud.',
  },
  'buff_sanity': {
    id: 'buff_sanity',
    speaker: 'Sistema',
    text: '[POTENCIADOR] Recuerdo estable: recuperas cordura.',
  },
  'buff_speed': {
    id: 'buff_speed',
    speaker: 'Sistema',
    text: '[POTENCIADOR] Adrenalina: Adrián se mueve un poco más rápido.',
  },
  'buff_resilience': {
    id: 'buff_resilience',
    speaker: 'Sistema',
    text: '[POTENCIADOR] Pulso firme: recuperas salud, cordura y stamina.',
  },
  'tape_required': {
    id: 'tape_required',
    speaker: 'Adrián',
    text: 'No puedo irme sin la cinta VHS. Tiene que haber una por aquí...',
  },

  // Level 2 - La Calle Nocturna
  'intro_l2_1': {
    id: 'intro_l2_1',
    speaker: 'Narrador',
    text: 'Las calles están vacías. La lluvia cae sin cesar. Adrián busca a la mujer de la cinta.',
    nextDialogueId: 'intro_l2_2',
  },
  'intro_l2_2': {
    id: 'intro_l2_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Encuentra a Lucía Torres. Cuidado con las sombras - se mueven en patrones. Usa los escondites (contenedores de basura) para evitarlas. La puerta del callejón necesita un código de 4 dígitos.]',
  },
  'code_hint_1': {
    id: 'code_hint_1',
    speaker: 'Adrián',
    text: 'Un grafiti en la pared... "Los muertos no olvidan: 19XX". La fecha del incendio del Orfeo fue 1987...',
    effect: 'reveal_code',
    effectData: '19',
  },
  'code_hint_2': {
    id: 'code_hint_2',
    speaker: 'Adrián',
    text: 'Una nota tirada... "El fuego consumió 87 almas". 87... eso completa el código: 1987.',
    effect: 'reveal_code',
    effectData: '87',
  },
  'lucia_1': {
    id: 'lucia_1',
    speaker: 'Lucía Torres',
    text: '¿Quién eres? ¿Por qué me sigues?',
    nextDialogueId: 'lucia_2',
  },
  'lucia_2': {
    id: 'lucia_2',
    speaker: 'Adrián',
    text: 'Tienes que irte de aquí. Estás en peligro. No puedo explicarlo ahora.',
    nextDialogueId: 'lucia_3',
  },
  'lucia_3': {
    id: 'lucia_3',
    speaker: 'Lucía Torres',
    text: '¿Cómo sabes mi nombre? Esto es muy extraño... Pero algo en tus ojos... te creo.',
  },
  'tape_2': {
    id: 'tape_2',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Una ferretería. Un hombre trabajando de noche. El ataque viene por detrás...',
    effect: 'add_tape',
  },
  'complete_2': {
    id: 'complete_2',
    speaker: 'Narrador',
    text: 'Lucía sobrevive gracias a Adrián. Pero al día siguiente, un taxista aparece muerto en las noticias...',
  },

  // Level 3 - La Ferreteria  
  'intro_l3_1': {
    id: 'intro_l3_1',
    speaker: 'Narrador',
    text: 'Jorge Gaitán, dueño de la ferretería. La próxima víctima según la cinta.',
    nextDialogueId: 'intro_l3_2',
  },
  'intro_l3_2': {
    id: 'intro_l3_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Salva a Jorge. La ferretería es un laberinto de estanterías. Debes activar 4 interruptores de luz en SECUENCIA para iluminar el camino. Un eco patrulla - escucha sus pasos.]',
  },
  'switch_wrong': {
    id: 'switch_wrong',
    speaker: 'Sistema',
    text: '[ERROR] Secuencia incorrecta. Los interruptores se han reiniciado. Pista: Sigue el orden de los colores en el póster de la entrada.',
  },
  'switch_correct': {
    id: 'switch_correct',
    speaker: 'Sistema',
    text: '[CORRECTO] Interruptor activado. Continúa la secuencia...',
  },
  'all_switches': {
    id: 'all_switches',
    speaker: 'Adrián',
    text: '¡Todas las luces encendidas! Ahora puedo llegar a Jorge.',
  },
  'jorge_1': {
    id: 'jorge_1',
    speaker: 'Jorge Gaitán',
    text: '¿Necesitas algo? Estoy por cerrar.',
    nextDialogueId: 'jorge_2',
  },
  'jorge_2': {
    id: 'jorge_2',
    speaker: 'Adrián',
    text: 'Señor Gaitán, tiene que salir de aquí. Alguien viene por usted.',
    nextDialogueId: 'jorge_3',
  },
  'jorge_3': {
    id: 'jorge_3',
    speaker: 'Jorge Gaitán',
    text: '¿Estás loco? ¿Quién eres tú para... espera, ese ruido...',
  },
  'tape_3': {
    id: 'tape_3',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Un puente peatonal. Una maestra caminando sola. Niebla espesa...',
    effect: 'add_tape',
  },
  'complete_3': {
    id: 'complete_3',
    speaker: 'Narrador',
    text: 'Otro salvado. Pero la paranoia de Adrián crece. ¿Quién envía estas cintas?',
  },

  // Level 4 - El Puente Peatonal
  'intro_l4_1': {
    id: 'intro_l4_1',
    speaker: 'Narrador',
    text: 'Marina Leal, maestra de escuela. El puente se extiende entre la niebla.',
    nextDialogueId: 'intro_l4_2',
  },
  'intro_l4_2': {
    id: 'intro_l4_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Cruza el puente y encuentra a Marina. PELIGRO: El puente tiene secciones eléctricas que se activan en patrón. Memoriza el ritmo: 3 segundos encendido, 2 segundos apagado.]',
  },
  'pattern_hint': {
    id: 'pattern_hint',
    speaker: 'Adrián',
    text: 'Las luces del puente... parpadean en secuencia. Debo cronometrar mis movimientos.',
  },
  'marina_1': {
    id: 'marina_1',
    speaker: 'Marina Leal',
    text: '¿Me conoces? Tu cara me resulta familiar...',
    nextDialogueId: 'marina_2',
  },
  'marina_2': {
    id: 'marina_2',
    speaker: 'Adrián',
    text: '¡No hay tiempo para explicaciones. Tiene que huir, ahora!',
  },
  'tape_4': {
    id: 'tape_4',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Un estacionamiento vacío. Un repartidor. Las sombras se mueven solas...',
    effect: 'add_tape',
  },
  'memory_1': {
    id: 'memory_1',
    speaker: '???',
    text: '...no me sueltes... por favor... ¡NO ME SUELTES!',
    effect: 'reveal_memory',
  },
  'complete_4': {
    id: 'complete_4',
    speaker: 'Adrián',
    text: '¿Qué fue esa voz? Me resulta... dolorosamente familiar.',
  },

  // Level 5 - El Estacionamiento
  'intro_l5_1': {
    id: 'intro_l5_1',
    speaker: 'Narrador',
    text: 'Camilo Cifuentes hace su última entrega del día. Las luces parpadean.',
    nextDialogueId: 'intro_l5_2',
  },
  'intro_l5_2': {
    id: 'intro_l5_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Encuentra a Camilo en el nivel B2. El estacionamiento tiene 3 niveles. Necesitas encontrar la tarjeta de acceso para cada nivel. ADVERTENCIA: El Operador aparece por primera vez - no puedes esconderte de él, solo huir.]',
  },
  'keycard_1': {
    id: 'keycard_1',
    speaker: 'Adrián',
    text: 'Tarjeta de acceso nivel B1. Debo buscar las otras.',
    effect: 'give_item',
    effectData: 'keycard_b1',
  },
  'keycard_2': {
    id: 'keycard_2',
    speaker: 'Adrián',
    text: 'Nivel B2... casi llego a Camilo.',
    effect: 'give_item',
    effectData: 'keycard_b2',
  },
  'camilo_1': {
    id: 'camilo_1',
    speaker: 'Camilo Cifuentes',
    text: 'Hey, ¿estás bien, amigo? Te ves terrible.',
    nextDialogueId: 'camilo_2',
  },
  'camilo_2': {
    id: 'camilo_2',
    speaker: 'Adrián',
    text: '¡No hay tiempo! ¡Corre!',
  },
  'tape_5': {
    id: 'tape_5',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Un hospital abandonado. Pasillos vacíos. Algo se arrastra en las sombras...',
    effect: 'add_tape',
  },
  'operator_appear': {
    id: 'operator_appear',
    speaker: '???',
    text: '[ESTÁTICA] YA CASI RECUERDAS [ESTÁTICA] LA VERDAD ESTÁ EN EL FUEGO [ESTÁTICA]',
    effect: 'reduce_sanity',
  },
  'complete_5': {
    id: 'complete_5',
    speaker: 'Narrador',
    text: 'Una figura de estática aparece brevemente. El Operador vigila...',
  },

  // Level 6 - El Hospital Abandonado
  'intro_l6_1': {
    id: 'intro_l6_1',
    speaker: 'Narrador',
    text: 'Marta Urrutia trabajaba aquí antes del cierre. Los pasillos guardan secretos.',
    nextDialogueId: 'intro_l6_2',
  },
  'intro_l6_2': {
    id: 'intro_l6_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Encuentra a Marta en el ala psiquiátrica. PUZZLE: Las puertas de las alas están cerradas con un sistema de válvulas. Debes ajustar 3 válvulas a los valores correctos (0-9). Pista: Los expedientes médicos contienen los números.]',
  },
  'medical_record_1': {
    id: 'medical_record_1',
    speaker: 'Adrián',
    text: 'Expediente #247... "Paciente admitido el día 7 del mes..." El primer número es 7.',
  },
  'medical_record_2': {
    id: 'medical_record_2',
    speaker: 'Adrián',
    text: 'Otro expediente... "3 víctimas de quemaduras del Orfeo ingresadas..." El segundo es 3.',
  },
  'medical_record_3': {
    id: 'medical_record_3',
    speaker: 'Adrián',
    text: 'El último... "Ala cerrada en el año 94, solo 1 enfermera permanece..." El tercero es 1. El código es 7-3-1.',
  },
  'valve_record_required': {
    id: 'valve_record_required',
    speaker: 'Sistema',
    text: '[ACCESO DENEGADO] Primero debes encontrar el expediente médico correspondiente para saber cómo ajustar esta válvula.',
  },
  'marta_1': {
    id: 'marta_1',
    speaker: 'Marta Urrutia',
    text: 'El incendio del Edificio Orfeo... yo trabajé con las víctimas. Niños, familias enteras...',
    nextDialogueId: 'marta_2',
  },
  'marta_2': {
    id: 'marta_2',
    speaker: 'Marta Urrutia',
    text: 'Hubo un niño... no pudieron identificarlo. Quemaduras en el 90% del cuerpo. Murió preguntando por su amigo.',
  },
  'tape_6': {
    id: 'tape_6',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Imágenes del Edificio Orfeo en llamas. Gritos. Un niño corre entre el humo...',
    effect: 'add_tape',
  },
  'memory_2': {
    id: 'memory_2',
    speaker: 'Voz de niño',
    text: '¡Mamá! ¡Papá! ¿Dónde están? ¡No veo nada!',
    effect: 'reveal_memory',
  },
  'complete_6': {
    id: 'complete_6',
    speaker: 'Adrián',
    text: 'El Edificio Orfeo... ¿por qué siento que ya estuve ahí?',
  },

  // Level 7 - La Estación
  'intro_l7_1': {
    id: 'intro_l7_1',
    speaker: 'Narrador',
    text: 'La investigación lleva a Adrián a un mural de conexiones. Todo apunta al Orfeo.',
    nextDialogueId: 'intro_l7_2',
  },
  'intro_l7_2': {
    id: 'intro_l7_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Encuentra a Gabriel Llorente. PUZZLE LÓGICO: La estación tiene 5 puertas, pero solo 1 lleva a Gabriel. Cada puerta tiene un símbolo. Debes leer las pistas en los carteles para deducir cuál es la correcta.]',
  },
  'logic_clue_1': {
    id: 'logic_clue_1',
    speaker: 'Adrián',
    text: 'Cartel 1: "La puerta del fuego no está junto a la del agua."',
  },
  'logic_clue_2': {
    id: 'logic_clue_2',
    speaker: 'Adrián',
    text: 'Cartel 2: "La verdad se encuentra entre la oscuridad y la luz."',
  },
  'logic_clue_3': {
    id: 'logic_clue_3',
    speaker: 'Adrián',
    text: 'Cartel 3: "El ojo que todo lo ve está en el centro."',
  },
  'wrong_door': {
    id: 'wrong_door',
    speaker: 'Sistema',
    text: '[TRAMPA] ¡Puerta incorrecta! Una sombra aparece...',
  },
  'logic_clues_required': {
    id: 'logic_clues_required',
    speaker: 'Sistema',
    text: '[BLOQUEADO] Primero lee las 3 pistas de la estacion antes de elegir una puerta.',
  },
  'logic_solved': {
    id: 'logic_solved',
    speaker: 'Sistema',
    text: '[CORRECTO] El OJO esta en el centro. La puerta se abre y revela la cinta.',
  },
  'gabriel_1': {
    id: 'gabriel_1',
    speaker: 'Gabriel Llorente',
    text: '¿Tú eres Adrián, verdad? He estado buscándote. Tenemos que hablar sobre mi hermano.',
    nextDialogueId: 'gabriel_2',
  },
  'gabriel_2': {
    id: 'gabriel_2',
    speaker: 'Adrián',
    text: '¿Tu hermano? No sé de qué hablas.',
    nextDialogueId: 'gabriel_3',
  },
  'gabriel_3': {
    id: 'gabriel_3',
    speaker: 'Gabriel Llorente',
    text: 'Nicolás Llorente. Murió en el incendio del Edificio Orfeo. Y tú estabas ahí esa noche.',
  },
  'tape_7': {
    id: 'tape_7',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Dos niños corren entre las llamas. Uno ayuda al otro. Luego... oscuridad.',
    effect: 'add_tape',
  },
  'complete_7': {
    id: 'complete_7',
    speaker: 'Adrián',
    text: 'Nicolás... ese nombre... ¿por qué me duele tanto escucharlo?',
  },

  // Level 8 - Edificio Orfeo Exterior
  'intro_l8_1': {
    id: 'intro_l8_1',
    speaker: 'Narrador',
    text: 'El Edificio Orfeo se alza como un cadáver de concreto y ceniza. Aquí comenzó todo.',
    nextDialogueId: 'intro_l8_2',
  },
  'intro_l8_2': {
    id: 'intro_l8_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Entra al Orfeo. DESAFÍO DE SIGILO: Múltiples enemigos patrullan el exterior. Usa las sombras y escondites. Si te detectan 3 veces, perderás. Encuentra la entrada secreta en el sótano.]',
  },
  'detection_warning': {
    id: 'detection_warning',
    speaker: 'Sistema',
    text: '[ALERTA] ¡Te han detectado! Intentos restantes: ',
  },
  'stealth_tip': {
    id: 'stealth_tip',
    speaker: 'Adrián',
    text: 'Debo moverme entre las sombras... Sprint hace ruido. Los enemigos escuchan.',
  },
  'basement_found': {
    id: 'basement_found',
    speaker: 'Adrián',
    text: 'Una entrada al sótano... Esta es la única forma de entrar.',
  },
  'tape_8': {
    id: 'tape_8',
    speaker: 'Sistema',
    text: '[CINTA VHS ENCONTRADA] Un niño sostiene la mano de otro. El fuego los rodea. "¡No me sueltes!"',
    effect: 'add_tape',
  },
  'memory_3': {
    id: 'memory_3',
    speaker: 'Adrián (niño)',
    text: '¡Mamá me llama! Tengo que ir... ¡SUÉLTAME!',
    effect: 'reveal_memory',
  },
  'complete_8': {
    id: 'complete_8',
    speaker: 'Adrián',
    text: 'Esa voz... soy yo. Soy yo de niño. ¿Qué hice esa noche?',
  },

  // Level 9 - Edificio Orfeo Interior
  'intro_l9_1': {
    id: 'intro_l9_1',
    speaker: 'Narrador',
    text: 'El interior del Orfeo guarda los ecos de esa noche. Las paredes recuerdan.',
    nextDialogueId: 'intro_l9_2',
  },
  'intro_l9_2': {
    id: 'intro_l9_2',
    speaker: 'Sistema',
    text: '[OBJETIVO: Llega al piso 7, la habitación donde todo terminó. PUZZLE FINAL: Reconstruye la secuencia de eventos activando 5 estaciones de memoria en el ORDEN CORRECTO de cómo sucedieron los hechos.]',
  },
  'memory_station_1': {
    id: 'memory_station_1',
    speaker: 'Eco del pasado',
    text: '"Los niños jugaban en el pasillo..."',
  },
  'memory_station_2': {
    id: 'memory_station_2',
    speaker: 'Eco del pasado',
    text: '"El humo comenzó a subir por las escaleras..."',
  },
  'memory_station_3': {
    id: 'memory_station_3',
    speaker: 'Eco del pasado',
    text: '"Adrián y Nicolás corrieron hacia la salida de emergencia..."',
  },
  'memory_station_4': {
    id: 'memory_station_4',
    speaker: 'Eco del pasado',
    text: '"El pasillo se derrumbó. Solo había espacio para uno..."',
  },
  'memory_station_5': {
    id: 'memory_station_5',
    speaker: 'Eco del pasado',
    text: '"Adrián soltó la mano de Nicolás..."',
  },
  'sequence_wrong': {
    id: 'sequence_wrong',
    speaker: 'El Operador',
    text: '[ESTÁTICA] NO PUEDES CAMBIAR EL ORDEN [ESTÁTICA] ACEPTA LA VERDAD [ESTÁTICA]',
  },
  'nicolas_1': {
    id: 'nicolas_1',
    speaker: 'Nicolás (Eco)',
    text: '¿Por qué me soltaste, Adrián? Prometiste que escaparíamos juntos...',
    nextDialogueId: 'nicolas_2',
  },
  'nicolas_2': {
    id: 'nicolas_2',
    speaker: 'Adrián',
    text: 'Nicolás... yo... lo siento tanto. Tenía miedo. Escuché a mis padres y...',
    nextDialogueId: 'nicolas_3',
  },
  'nicolas_3': {
    id: 'nicolas_3',
    speaker: 'Nicolás (Eco)',
    text: 'Me empujaste. Caí entre las llamas. Y tú también moriste minutos después.',
  },
  'tape_9': {
    id: 'tape_9',
    speaker: 'Sistema',
    text: '[CINTA VHS FINAL] La verdad completa. Adrián empuja a Nicolás. Ambos mueren en el incendio. Todo fue un bucle de culpa.',
    effect: 'add_tape',
  },
  'complete_9': {
    id: 'complete_9',
    speaker: 'Adrián',
    text: '¿Estoy... muerto? ¿Todo esto... solo existe en mi mente? ¿Un ciclo infinito de culpa?',
  },

  // Level 10 - La Verdad Final
  'intro_l10_1': {
    id: 'intro_l10_1',
    speaker: 'Narrador',
    text: 'El momento de la verdad. Adrián debe confrontar al Operador... a sí mismo.',
    nextDialogueId: 'intro_l10_2',
  },
  'intro_l10_2': {
    id: 'intro_l10_2',
    speaker: 'Sistema',
    text: '[OBJETIVO FINAL: Confronta al Operador. No puedes correr. No puedes esconderte. Solo puedes ENFRENTAR la verdad. Responde a sus preguntas con honestidad para romper el ciclo.]',
  },
  'operator_question_1': {
    id: 'operator_question_1',
    speaker: 'El Operador',
    text: '[ESTÁTICA] PRIMERA PREGUNTA [ESTÁTICA] ¿QUÉ SENTISTE CUANDO SOLTASTE SU MANO?',
    choices: [
      { text: 'Miedo', nextDialogueId: 'answer_correct_1' },
      { text: 'Nada', nextDialogueId: 'answer_wrong_1' },
      { text: 'Alivio', nextDialogueId: 'answer_correct_1' },
    ],
  },
  'answer_correct_1': {
    id: 'answer_correct_1',
    speaker: 'El Operador',
    text: '[ESTÁTICA] HONESTO [ESTÁTICA] SIGUIENTE PREGUNTA...',
    nextDialogueId: 'operator_question_2',
  },
  'answer_wrong_1': {
    id: 'answer_wrong_1',
    speaker: 'El Operador',
    text: '[ESTÁTICA] MENTIRA [ESTÁTICA] EL CICLO CONTINÚA...',
    effect: 'reduce_sanity',
    nextDialogueId: 'operator_question_1',
  },
  'operator_question_2': {
    id: 'operator_question_2',
    speaker: 'El Operador',
    text: '[ESTÁTICA] SEGUNDA PREGUNTA [ESTÁTICA] ¿POR QUÉ SALVASTE A LOS DEMÁS?',
    choices: [
      { text: 'Para redimirme', nextDialogueId: 'answer_correct_2' },
      { text: 'Porque soy un héroe', nextDialogueId: 'answer_wrong_2' },
      { text: 'Para escapar de la culpa', nextDialogueId: 'answer_correct_2' },
    ],
  },
  'answer_correct_2': {
    id: 'answer_correct_2',
    speaker: 'El Operador',
    text: '[ESTÁTICA] LA VERDAD EMERGE [ESTÁTICA]',
    nextDialogueId: 'operator_question_3',
  },
  'answer_wrong_2': {
    id: 'answer_wrong_2',
    speaker: 'El Operador',
    text: '[ESTÁTICA] ORGULLO FALSO [ESTÁTICA]',
    effect: 'reduce_sanity',
    nextDialogueId: 'operator_question_2',
  },
  'operator_question_3': {
    id: 'operator_question_3',
    speaker: 'El Operador',
    text: '[ESTÁTICA] PREGUNTA FINAL [ESTÁTICA] ¿ACEPTAS LO QUE HICISTE?',
    choices: [
      { text: 'Sí, lo acepto', nextDialogueId: 'final_truth' },
      { text: 'No fue mi culpa', nextDialogueId: 'cycle_repeat' },
      { text: 'Merezco este infierno', nextDialogueId: 'final_truth' },
    ],
  },
  'cycle_repeat': {
    id: 'cycle_repeat',
    speaker: 'El Operador',
    text: '[ESTÁTICA] ENTONCES EL CICLO CONTINÚA [ESTÁTICA] POR SIEMPRE [ESTÁTICA]',
    effect: 'reduce_sanity',
    nextDialogueId: 'operator_question_3',
  },
  'final_truth': {
    id: 'final_truth',
    speaker: 'Adrián',
    text: 'Fui yo. Lo solté porque tenía miedo. Y morí también esa noche. Todo esto... son mis recuerdos, mi culpa, mi prisión.',
    nextDialogueId: 'final_truth_2',
  },
  'final_truth_2': {
    id: 'final_truth_2',
    speaker: 'Adrián',
    text: 'Pero ya no quiero huir más. Acepto lo que hice. Acepto la verdad.',
    effect: 'trigger_event',
    effectData: 'solve_truth_puzzle',
    nextDialogueId: 'nicolas_final',
  },
  'nicolas_final': {
    id: 'nicolas_final',
    speaker: 'Nicolás',
    text: 'Adrián... ya es hora de descansar. Ven con nosotros.',
    nextDialogueId: 'gabriel_final',
  },
  'gabriel_final': {
    id: 'gabriel_final',
    speaker: 'Gabriel Llorente',
    text: 'El ciclo se rompe. Ya no tienes que cargar esta culpa solo.',
    nextDialogueId: 'ending',
  },
  'ending': {
    id: 'ending',
    speaker: 'Narrador',
    text: 'Adrián cruza la puerta de luz. El Edificio Orfeo se vacía. Los ecos desaparecen. Las cintas pierden significado. Finalmente... paz.',
  },

  // Hint dialogues
  'hint_generic': {
    id: 'hint_generic',
    speaker: 'Sistema',
    text: '[PISTA] Explora el área cuidadosamente. Las respuestas están escondidas en los detalles.',
  },
}

// Level definitions with complex puzzles
export const levels: Level[] = [
  // Level 1 - El Apartamento (Tutorial level with fuse puzzle)
  {
    id: 1,
    name: 'El Apartamento',
    description: 'Una caja misteriosa espera frente a la puerta de Adrián.',
    objective: 'Encuentra los 3 fusibles e insértalos en la caja de fusibles en el orden correcto (2-1-3) para restaurar la luz y encontrar la cinta VHS.',
    width: 900,
    height: 700,
    playerStart: { x: 100, y: 350 },
    backgroundColor: '#0a0a12',
    ambientColor: '#05050a',
    litBackgroundColor: '#161821',
    litAmbientColor: '#232638',
    fogOfWar: true,
    visibilityRadius: 165,
    isDark: true,
    lightsOn: false,
    requiresLightToExit: true,
    obstacles: [
      // Walls
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 900, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 660 }, width: 900, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 700, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 860, y: 0 }, width: 40, height: 700, solid: true },
      // Interior walls creating rooms
      { id: 'wall_h1', type: 'wall', position: { x: 300, y: 40 }, width: 20, height: 200, solid: true },
      { id: 'wall_h2', type: 'wall', position: { x: 300, y: 340 }, width: 20, height: 200, solid: true },
      { id: 'wall_h3', type: 'wall', position: { x: 550, y: 200 }, width: 20, height: 300, solid: true },
      { id: 'wall_h4', type: 'wall', position: { x: 550, y: 600 }, width: 310, height: 20, solid: true },
      // Furniture
      { id: 'sofa', type: 'furniture', position: { x: 80, y: 480 }, width: 140, height: 60, solid: true },
      { id: 'tv_stand', type: 'furniture', position: { x: 100, y: 80 }, width: 100, height: 40, solid: true },
      { id: 'table', type: 'furniture', position: { x: 380, y: 120 }, width: 100, height: 60, solid: true },
      { id: 'bed', type: 'furniture', position: { x: 620, y: 80 }, width: 180, height: 100, solid: true },
      { id: 'closet', type: 'furniture', position: { x: 750, y: 250 }, width: 80, height: 120, solid: true },
      { id: 'desk', type: 'furniture', position: { x: 620, y: 400 }, width: 120, height: 60, solid: true },
      // Exit door (locked)
      { id: 'exit_door', type: 'door', position: { x: 800, y: 300 }, width: 60, height: 80, solid: true, isOpen: false, requiresKey: 'fusebox_complete' },
    ],
    enemies: [
      { id: 'apartment_shadow_1', type: 'shadow', position: { x: 650, y: 180 }, width: 26, height: 34, speed: 1.1, direction: 'down', isActive: true, detectionRadius: 75, patrolPath: [{ x: 650, y: 180 }, { x: 650, y: 420 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 70, stunned: false, stunnedTimer: 0 },
      { id: 'apartment_echo_1', type: 'echo', position: { x: 250, y: 520 }, width: 24, height: 32, speed: 0.9, direction: 'right', isActive: true, detectionRadius: 65, patrolPath: [{ x: 180, y: 520 }, { x: 500, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'apartment_shadow_2', type: 'shadow', position: { x: 420, y: 610 }, width: 26, height: 34, speed: 1.0, direction: 'left', isActive: true, detectionRadius: 70, patrolPath: [{ x: 350, y: 610 }, { x: 740, y: 610 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 65, stunned: false, stunnedTimer: 0 },
      { id: 'apartment_echo_2', type: 'echo', position: { x: 780, y: 260 }, width: 24, height: 32, speed: 0.95, direction: 'down', isActive: true, detectionRadius: 64, patrolPath: [{ x: 780, y: 220 }, { x: 780, y: 430 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'apartment_shadow_3', type: 'shadow', position: { x: 180, y: 340 }, width: 26, height: 34, speed: 0.95, direction: 'down', isActive: true, detectionRadius: 66, patrolPath: [{ x: 180, y: 250 }, { x: 180, y: 560 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 60, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'fuse_1', type: 'fuse', position: { x: 150, y: 580 }, width: 20, height: 20, collected: false, dialogueId: 'fuse_1_found', hidden: false, inventoryItem: { id: 'fuse_1', type: 'fuse', name: 'Fusible #2', description: 'Un fusible con el número 2 grabado.' } },
      { id: 'fuse_2', type: 'fuse', position: { x: 420, y: 200 }, width: 20, height: 20, collected: false, dialogueId: 'fuse_2_found', hidden: false, inventoryItem: { id: 'fuse_2', type: 'fuse', name: 'Fusible #1', description: 'Un fusible con el número 1 grabado.' } },
      { id: 'fuse_3', type: 'fuse', position: { x: 700, y: 500 }, width: 20, height: 20, collected: false, dialogueId: 'fuse_3_found', hidden: false, inventoryItem: { id: 'fuse_3', type: 'fuse', name: 'Fusible #3', description: 'Un fusible con el número 3 grabado.' } },
      { id: 'tape_1', type: 'vhs_tape', position: { x: 120, y: 100 }, width: 24, height: 24, collected: false, dialogueId: 'tape_1', hidden: true, revealedBy: 'fusebox_puzzle' },
    ],
    npcs: [],
    switches: [
      { id: 'fusebox', type: 'fuse_box', position: { x: 350, y: 550 }, width: 40, height: 60, isActivated: false, linkedTo: ['exit_door', 'tape_1'], requiresItem: 'fuse' },
    ],
    puzzles: [
      {
        id: 'fusebox_puzzle',
        type: 'sequence',
        name: 'Caja de Fusibles',
        description: 'Inserta los 3 fusibles en el orden correcto',
        hint: 'Los números en los fusibles indican el orden: 2-1-3',
        isSolved: false,
        sequenceSwitches: ['fuse_1', 'fuse_2', 'fuse_3'],
        currentSequenceIndex: 0,
        unlocksDoor: 'exit_door',
        unlocksCollectible: 'tape_1',
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_1', text: 'Los fusibles tienen números grabados. Ese es el orden.', triggerCondition: 'time', conditionValue: 60, hasBeenShown: false },
      { id: 'hint_2', text: 'La caja de fusibles está en la sala principal.', triggerCondition: 'deaths', conditionValue: 2, hasBeenShown: false },
    ],
    hidingSpots: [],
    darkMazeWalls: [
      { id: 'dark_maze_1', type: 'wall', position: { x: 180, y: 150 }, width: 20, height: 280, solid: true },
      { id: 'dark_maze_2', type: 'wall', position: { x: 180, y: 150 }, width: 180, height: 20, solid: true },
      { id: 'dark_maze_3', type: 'wall', position: { x: 340, y: 250 }, width: 180, height: 20, solid: true },
      { id: 'dark_maze_4', type: 'wall', position: { x: 460, y: 250 }, width: 20, height: 210, solid: true },
      { id: 'dark_maze_5', type: 'wall', position: { x: 620, y: 260 }, width: 20, height: 220, solid: true },
      { id: 'dark_maze_6', type: 'wall', position: { x: 620, y: 460 }, width: 160, height: 20, solid: true },
    ],
    exitPosition: { x: 800, y: 300 },
    exitWidth: 60,
    exitHeight: 80,
    exitLocked: true,
    exitUnlockedBy: 'fusebox_puzzle',
    introDialogueIds: ['intro_1', 'intro_2', 'intro_3', 'intro_4'],
    completionDialogueIds: ['complete_1'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
    decorations: [
      { id: 'crack_1', type: 'crack', position: { x: 320, y: 100 }, width: 40, height: 40, opacity: 0.4 },
      { id: 'poster_1', type: 'poster', position: { x: 400, y: 50 }, width: 30, height: 45, rotation: 5 },
      { id: 'plant_1', type: 'plant', position: { x: 800, y: 550 }, width: 32, height: 48 },
      { id: 'blood_1', type: 'blood', position: { x: 350, y: 560 }, width: 50, height: 30, opacity: 0.3 },
      { id: 'trash_1', type: 'trash', position: { x: 120, y: 600 }, width: 24, height: 16 },
    ],
  },
  // Level 2 - La Calle Nocturna (Stealth + Code puzzle)
  {
    id: 2,
    name: 'La Calle Nocturna',
    description: 'Salva a Lucía Torres antes de que sea tarde.',
    objective: 'Encuentra las 2 pistas del código (1987) para abrir la puerta del callejón. Evita las sombras usando los escondites.',
    width: 1200,
    height: 800,
    playerStart: { x: 80, y: 400 },
    backgroundColor: '#0a0e14',
    ambientColor: '#050810',
    fogOfWar: false,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1200, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 760 }, width: 1200, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 800, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 1160, y: 0 }, width: 40, height: 800, solid: true },
      // Street obstacles
      { id: 'car_1', type: 'furniture', position: { x: 200, y: 150 }, width: 120, height: 60, solid: true },
      { id: 'car_2', type: 'furniture', position: { x: 500, y: 500 }, width: 120, height: 60, solid: true },
      { id: 'car_3', type: 'furniture', position: { x: 800, y: 200 }, width: 120, height: 60, solid: true },
      // Hiding spots (dumpsters)
      { id: 'dumpster_1', type: 'hiding_spot', position: { x: 350, y: 100 }, width: 60, height: 50, solid: true, canHideIn: true },
      { id: 'dumpster_2', type: 'hiding_spot', position: { x: 650, y: 400 }, width: 60, height: 50, solid: true, canHideIn: true },
      { id: 'dumpster_3', type: 'hiding_spot', position: { x: 300, y: 600 }, width: 60, height: 50, solid: true, canHideIn: true },
      // Alley door (locked with code)
      { id: 'alley_door', type: 'door', position: { x: 900, y: 350 }, width: 60, height: 100, solid: true, isOpen: false, requiresCode: '1987' },
      // Walls creating alley
      { id: 'alley_wall_1', type: 'wall', position: { x: 850, y: 250 }, width: 20, height: 120, solid: true },
      { id: 'alley_wall_2', type: 'wall', position: { x: 850, y: 450 }, width: 20, height: 150, solid: true },
    ],
    enemies: [
      { id: 'shadow_1', type: 'shadow', position: { x: 400, y: 300 }, width: 28, height: 36, speed: 1.8, direction: 'right', isActive: true, detectionRadius: 100, patrolPath: [{ x: 400, y: 300 }, { x: 600, y: 300 }, { x: 600, y: 500 }, { x: 400, y: 500 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 80, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_2', type: 'shadow', position: { x: 700, y: 150 }, width: 28, height: 36, speed: 1.5, direction: 'down', isActive: true, detectionRadius: 90, patrolPath: [{ x: 700, y: 150 }, { x: 700, y: 350 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 70, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_3', type: 'shadow', position: { x: 930, y: 600 }, width: 28, height: 36, speed: 1.4, direction: 'left', isActive: true, detectionRadius: 85, patrolPath: [{ x: 780, y: 600 }, { x: 1080, y: 600 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 75, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_alley', type: 'shadow', position: { x: 1040, y: 260 }, width: 26, height: 34, speed: 1.2, direction: 'down', isActive: true, detectionRadius: 80, patrolPath: [{ x: 1040, y: 220 }, { x: 1040, y: 460 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_rooftop_1', type: 'shadow', position: { x: 520, y: 680 }, width: 28, height: 36, speed: 1.65, direction: 'right', isActive: true, detectionRadius: 95, patrolPath: [{ x: 420, y: 680 }, { x: 760, y: 680 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 90, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_rooftop_2', type: 'shadow', position: { x: 980, y: 160 }, width: 28, height: 36, speed: 1.55, direction: 'left', isActive: true, detectionRadius: 90, patrolPath: [{ x: 860, y: 160 }, { x: 1100, y: 160 }, { x: 1100, y: 300 }, { x: 860, y: 300 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 85, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_crosswalk', type: 'shadow', position: { x: 250, y: 450 }, width: 26, height: 34, speed: 1.45, direction: 'down', isActive: true, detectionRadius: 85, patrolPath: [{ x: 250, y: 320 }, { x: 250, y: 650 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 80, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'clue_code_1', type: 'document', position: { x: 250, y: 200 }, width: 20, height: 24, collected: false, dialogueId: 'code_hint_1', hidden: false },
      { id: 'clue_code_2', type: 'document', position: { x: 750, y: 600 }, width: 20, height: 24, collected: false, dialogueId: 'code_hint_2', hidden: false },
      { id: 'buff_l2_stamina', type: 'tool', position: { x: 360, y: 180 }, width: 24, height: 24, collected: false, dialogueId: 'buff_stamina', hidden: false, buff: { stamina: 40 } },
      { id: 'tape_2', type: 'vhs_tape', position: { x: 1050, y: 400 }, width: 24, height: 24, collected: false, dialogueId: 'tape_2', hidden: false },
    ],
    npcs: [
      { id: 'lucia', name: 'Lucía Torres', position: { x: 1000, y: 400 }, width: 24, height: 32, dialogueIds: ['lucia_1', 'lucia_2', 'lucia_3'], currentDialogueIndex: 0, sprite: 'npc_female' },
    ],
    switches: [
      { id: 'keypad_1', type: 'keypad', position: { x: 880, y: 380 }, width: 30, height: 40, isActivated: false, linkedTo: ['alley_door'], code: '1987' },
    ],
    puzzles: [
      {
        id: 'code_puzzle',
        type: 'code',
        name: 'Puerta del Callejón',
        description: 'Introduce el código de 4 dígitos',
        hint: 'El año del incendio del Orfeo...',
        isSolved: false,
        correctCode: '1987',
        enteredCode: '',
        unlocksDoor: 'alley_door',
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_stealth', text: 'Mantén Shift presionado para esconderte en los contenedores.', triggerCondition: 'deaths', conditionValue: 1, hasBeenShown: false },
    ],
    hidingSpots: [{ x: 350, y: 100 }, { x: 650, y: 400 }, { x: 300, y: 600 }],
    exitPosition: { x: 1100, y: 380 },
    exitWidth: 50,
    exitHeight: 80,
    exitLocked: false,
    introDialogueIds: ['intro_l2_1', 'intro_l2_2'],
    completionDialogueIds: ['complete_2'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
    decorations: [
      { id: 'crack_street_1', type: 'crack', position: { x: 100, y: 50 }, width: 60, height: 60, opacity: 0.3 },
      { id: 'blood_street_1', type: 'blood', position: { x: 950, y: 420 }, width: 80, height: 40, opacity: 0.5 },
      { id: 'poster_street_1', type: 'poster', position: { x: 860, y: 260 }, width: 25, height: 35, rotation: -10 },
      { id: 'puddle_1', type: 'puddle', position: { x: 300, y: 300 }, width: 120, height: 40, opacity: 0.4 },
      { id: 'cables_1', type: 'cables', position: { x: 50, y: 700 }, width: 200, height: 20, opacity: 0.6 },
      { id: 'trash_street_1', type: 'trash', position: { x: 380, y: 130 }, width: 30, height: 20 },
    ],
  },
  // Level 3 - La Ferreteria (Sequence puzzle)
  {
    id: 3,
    name: 'La Ferretería',
    description: 'Jorge Gaitán trabaja de noche. El peligro acecha.',
    objective: 'Activa los 4 interruptores de luz en el orden correcto según los colores del póster: ROJO-AZUL-VERDE-AMARILLO.',
    width: 1000,
    height: 800,
    playerStart: { x: 100, y: 700 },
    backgroundColor: '#12121a',
    ambientColor: '#08080f',
    fogOfWar: false,
    visibilityRadius: 180,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1000, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 760 }, width: 1000, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 800, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 960, y: 0 }, width: 40, height: 800, solid: true },
      // Shelving units creating maze
      { id: 'shelf_1', type: 'furniture', position: { x: 150, y: 100 }, width: 50, height: 300, solid: true },
      { id: 'shelf_2', type: 'furniture', position: { x: 300, y: 100 }, width: 50, height: 250, solid: true },
      { id: 'shelf_3', type: 'furniture', position: { x: 450, y: 150 }, width: 50, height: 300, solid: true },
      { id: 'shelf_4', type: 'furniture', position: { x: 600, y: 100 }, width: 50, height: 250, solid: true },
      { id: 'shelf_5', type: 'furniture', position: { x: 750, y: 200 }, width: 50, height: 200, solid: true },
      { id: 'shelf_6', type: 'furniture', position: { x: 200, y: 500 }, width: 300, height: 50, solid: true },
      { id: 'shelf_7', type: 'furniture', position: { x: 600, y: 500 }, width: 250, height: 50, solid: true },
      { id: 'counter', type: 'furniture', position: { x: 800, y: 600 }, width: 140, height: 60, solid: true },
    ],
    enemies: [
      { id: 'echo_1', type: 'echo', position: { x: 500, y: 350 }, width: 26, height: 34, speed: 1.5, direction: 'right', isActive: true, detectionRadius: 100, patrolPath: [{ x: 250, y: 350 }, { x: 700, y: 350 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 120, stunned: false, stunnedTimer: 0 },
      { id: 'echo_2', type: 'echo', position: { x: 300, y: 620 }, width: 26, height: 34, speed: 1.25, direction: 'right', isActive: true, detectionRadius: 90, patrolPath: [{ x: 180, y: 620 }, { x: 520, y: 620 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 110, stunned: false, stunnedTimer: 0 },
      { id: 'echo_3', type: 'echo', position: { x: 820, y: 260 }, width: 26, height: 34, speed: 1.1, direction: 'down', isActive: true, detectionRadius: 85, patrolPath: [{ x: 820, y: 160 }, { x: 820, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 100, stunned: false, stunnedTimer: 0 },
      { id: 'echo_4', type: 'echo', position: { x: 210, y: 270 }, width: 26, height: 34, speed: 1.35, direction: 'down', isActive: true, detectionRadius: 92, patrolPath: [{ x: 210, y: 120 }, { x: 210, y: 430 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 115, stunned: false, stunnedTimer: 0 },
      { id: 'echo_5', type: 'echo', position: { x: 610, y: 620 }, width: 26, height: 34, speed: 1.3, direction: 'right', isActive: true, detectionRadius: 92, patrolPath: [{ x: 540, y: 620 }, { x: 900, y: 620 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 112, stunned: false, stunnedTimer: 0 },
      { id: 'hardware_shadow_1', type: 'shadow', position: { x: 690, y: 420 }, width: 28, height: 36, speed: 1.18, direction: 'left', isActive: true, detectionRadius: 82, patrolPath: [{ x: 520, y: 420 }, { x: 860, y: 420 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'hardware_shadow_2', type: 'shadow', position: { x: 360, y: 210 }, width: 28, height: 36, speed: 1.12, direction: 'down', isActive: true, detectionRadius: 80, patrolPath: [{ x: 360, y: 120 }, { x: 360, y: 460 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'buff_l3_speed', type: 'tool', position: { x: 210, y: 450 }, width: 24, height: 24, collected: false, dialogueId: 'buff_speed', hidden: false, buff: { speed: 0.15, stamina: 25 } },
      { id: 'buff_l3_health', type: 'tool', position: { x: 760, y: 610 }, width: 24, height: 24, collected: false, dialogueId: 'buff_health', hidden: false, buff: { health: 25 } },
      { id: 'tape_3', type: 'vhs_tape', position: { x: 850, y: 150 }, width: 24, height: 24, collected: false, dialogueId: 'tape_3', hidden: true, revealedBy: 'sequence_puzzle' },
    ],
    npcs: [
      { id: 'jorge', name: 'Jorge Gaitán', position: { x: 850, y: 650 }, width: 24, height: 32, dialogueIds: ['jorge_1', 'jorge_2', 'jorge_3'], currentDialogueIndex: 0, sprite: 'npc_male', isBlocking: false },
    ],
    switches: [
      { id: 'switch_red', type: 'lever', position: { x: 180, y: 420 }, width: 30, height: 40, isActivated: false, linkedTo: [], correctSequenceIndex: 0 },
      { id: 'switch_blue', type: 'lever', position: { x: 350, y: 80 }, width: 30, height: 40, isActivated: false, linkedTo: [], correctSequenceIndex: 1 },
      { id: 'switch_green', type: 'lever', position: { x: 550, y: 470 }, width: 30, height: 40, isActivated: false, linkedTo: [], correctSequenceIndex: 2 },
      { id: 'switch_yellow', type: 'lever', position: { x: 720, y: 120 }, width: 30, height: 40, isActivated: false, linkedTo: [], correctSequenceIndex: 3 },
    ],
    puzzles: [
      {
        id: 'sequence_puzzle',
        type: 'sequence',
        name: 'Secuencia de Luces',
        description: 'Activa los interruptores en el orden correcto',
        hint: 'El poster en la entrada muestra: ROJO, AZUL, VERDE, AMARILLO',
        isSolved: false,
        sequenceSwitches: ['switch_red', 'switch_blue', 'switch_green', 'switch_yellow'],
        currentSequenceIndex: 0,
        unlocksCollectible: 'tape_3',
        unlocksExit: true,
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_sequence', text: 'Busca el poster con colores cerca de la entrada.', triggerCondition: 'stuck', conditionValue: 30, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 920, y: 700 },
    exitWidth: 40,
    exitHeight: 60,
    exitLocked: true,
    exitUnlockedBy: 'sequence_puzzle',
    introDialogueIds: ['intro_l3_1', 'intro_l3_2'],
    completionDialogueIds: ['complete_3'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 4 - El Puente Peatonal (Timing puzzle)
  {
    id: 4,
    name: 'El Puente Peatonal',
    description: 'Marina Leal cruza el puente entre la niebla. Los recuerdos despiertan.',
    objective: 'Cruza el puente evitando las zonas eléctricas. Patrón: 3 segundos ON, 2 segundos OFF. Encuentra el fragmento de memoria.',
    width: 1400,
    height: 500,
    playerStart: { x: 80, y: 250 },
    backgroundColor: '#101520',
    ambientColor: '#080a10',
    fogOfWar: false,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1400, height: 60, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 440 }, width: 1400, height: 60, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 60, height: 500, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 1340, y: 0 }, width: 60, height: 500, solid: true },
      // Bridge rails
      { id: 'rail_top', type: 'wall', position: { x: 150, y: 100 }, width: 1100, height: 20, solid: true },
      { id: 'rail_bottom', type: 'wall', position: { x: 150, y: 380 }, width: 1100, height: 20, solid: true },
    ],
    enemies: [
      { id: 'shadow_bridge', type: 'shadow', position: { x: 700, y: 250 }, width: 28, height: 36, speed: 2.5, direction: 'left', isActive: true, detectionRadius: 80, patrolPath: [{ x: 300, y: 250 }, { x: 1100, y: 250 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_bridge_2', type: 'shadow', position: { x: 420, y: 180 }, width: 26, height: 34, speed: 1.8, direction: 'right', isActive: true, detectionRadius: 70, patrolPath: [{ x: 260, y: 180 }, { x: 620, y: 180 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_bridge_3', type: 'shadow', position: { x: 980, y: 320 }, width: 26, height: 34, speed: 1.7, direction: 'left', isActive: true, detectionRadius: 70, patrolPath: [{ x: 820, y: 320 }, { x: 1220, y: 320 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_bridge_4', type: 'shadow', position: { x: 560, y: 130 }, width: 26, height: 34, speed: 1.95, direction: 'right', isActive: true, detectionRadius: 72, patrolPath: [{ x: 360, y: 130 }, { x: 820, y: 130 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_bridge_5', type: 'shadow', position: { x: 1180, y: 250 }, width: 28, height: 36, speed: 2.15, direction: 'left', isActive: true, detectionRadius: 78, patrolPath: [{ x: 900, y: 250 }, { x: 1260, y: 250 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'bridge_echo_1', type: 'echo', position: { x: 760, y: 370 }, width: 26, height: 34, speed: 1.4, direction: 'left', isActive: true, detectionRadius: 70, patrolPath: [{ x: 520, y: 370 }, { x: 1060, y: 370 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 90, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'buff_l4_health', type: 'tool', position: { x: 380, y: 250 }, width: 24, height: 24, collected: false, dialogueId: 'buff_health', hidden: false, buff: { health: 30 } },
      { id: 'buff_l4_stamina', type: 'tool', position: { x: 820, y: 250 }, width: 24, height: 24, collected: false, dialogueId: 'buff_stamina', hidden: false, buff: { stamina: 50 } },
      { id: 'tape_4', type: 'vhs_tape', position: { x: 1200, y: 250 }, width: 24, height: 24, collected: false, dialogueId: 'tape_4', hidden: false },
      { id: 'memory_fragment_1', type: 'memory_fragment', position: { x: 650, y: 300 }, width: 24, height: 24, collected: false, dialogueId: 'memory_1', hidden: false },
    ],
    npcs: [
      { id: 'marina', name: 'Marina Leal', position: { x: 1250, y: 230 }, width: 24, height: 32, dialogueIds: ['marina_1', 'marina_2'], currentDialogueIndex: 0, sprite: 'npc_female' },
    ],
    switches: [],
    puzzles: [
      {
        id: 'timing_puzzle',
        type: 'timing',
        name: 'Puente Electrico',
        description: 'Cruza cuando las zonas eléctricas estén desactivadas',
        hint: 'Patrón: 3 segundos encendido, 2 segundos apagado. ¡Cuenta!',
        isSolved: false,
        timeLimit: 0,
        unlocksExit: false,
      },
    ],
    pressurePlates: [],
    hazardZones: [
      { id: 'electric_1', type: 'electric', position: { x: 250, y: 120 }, width: 100, height: 260, isActive: true, pattern: 'timed', onDuration: 180, offDuration: 120, currentTimer: 0, damage: 15 },
      { id: 'electric_2', type: 'electric', position: { x: 450, y: 120 }, width: 100, height: 260, isActive: false, pattern: 'timed', onDuration: 180, offDuration: 120, currentTimer: 90, damage: 15 },
      { id: 'electric_3', type: 'electric', position: { x: 650, y: 120 }, width: 100, height: 260, isActive: true, pattern: 'timed', onDuration: 180, offDuration: 120, currentTimer: 0, damage: 15 },
      { id: 'electric_4', type: 'electric', position: { x: 850, y: 120 }, width: 100, height: 260, isActive: false, pattern: 'timed', onDuration: 180, offDuration: 120, currentTimer: 90, damage: 15 },
      { id: 'electric_5', type: 'electric', position: { x: 1050, y: 120 }, width: 100, height: 260, isActive: true, pattern: 'timed', onDuration: 180, offDuration: 120, currentTimer: 0, damage: 15 },
    ],
    hints: [
      { id: 'hint_timing', text: 'Las zonas alternas tienen patrones opuestos. Cuando una se apaga, la otra se enciende.', triggerCondition: 'deaths', conditionValue: 3, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 1300, y: 220 },
    exitWidth: 40,
    exitHeight: 60,
    exitLocked: false,
    introDialogueIds: ['intro_l4_1', 'intro_l4_2'],
    completionDialogueIds: ['complete_4'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 5 - El Estacionamiento (Multi-level with keycards)
  {
    id: 5,
    name: 'El Estacionamiento',
    description: 'Camilo hace su ultima entrega. El Operador aparece.',
    objective: 'Encuentra las tarjetas de acceso B1 y B2 para llegar al nivel inferior. El Operador te persigue - no puedes esconderte de él.',
    width: 1100,
    height: 900,
    playerStart: { x: 100, y: 100 },
    backgroundColor: '#303846',
    ambientColor: '#222a36',
    fogOfWar: false,
    visibilityRadius: 420,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1100, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 860 }, width: 1100, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 900, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 1060, y: 0 }, width: 40, height: 900, solid: true },
      // Level dividers
      { id: 'level_div_1', type: 'wall', position: { x: 40, y: 280 }, width: 900, height: 20, solid: true },
      { id: 'level_div_2', type: 'wall', position: { x: 160, y: 580 }, width: 900, height: 20, solid: true },
      // Cars
      { id: 'car_1', type: 'furniture', position: { x: 150, y: 80 }, width: 100, height: 60, solid: true },
      { id: 'car_2', type: 'furniture', position: { x: 350, y: 80 }, width: 100, height: 60, solid: true },
      { id: 'car_3', type: 'furniture', position: { x: 550, y: 80 }, width: 100, height: 60, solid: true },
      { id: 'car_4', type: 'furniture', position: { x: 200, y: 350 }, width: 100, height: 60, solid: true },
      { id: 'car_5', type: 'furniture', position: { x: 450, y: 400 }, width: 100, height: 60, solid: true },
      { id: 'car_6', type: 'furniture', position: { x: 700, y: 350 }, width: 100, height: 60, solid: true },
      { id: 'car_7', type: 'furniture', position: { x: 300, y: 650 }, width: 100, height: 60, solid: true },
      { id: 'car_8', type: 'furniture', position: { x: 600, y: 700 }, width: 100, height: 60, solid: true },
      // Doors between levels
      { id: 'door_b1', type: 'door', position: { x: 950, y: 200 }, width: 60, height: 80, solid: true, isOpen: false, requiresKey: 'keycard_b1' },
      { id: 'door_b2', type: 'door', position: { x: 80, y: 500 }, width: 60, height: 80, solid: true, isOpen: false, requiresKey: 'keycard_b2' },
    ],
    enemies: [
      { id: 'operator_1', type: 'operator', position: { x: 800, y: 500 }, width: 32, height: 42, speed: 1.2, direction: 'left', isActive: true, detectionRadius: 200, behaviorState: 'chase', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_parking', type: 'shadow', position: { x: 400, y: 700 }, width: 28, height: 36, speed: 1.6, direction: 'right', isActive: true, detectionRadius: 90, patrolPath: [{ x: 200, y: 700 }, { x: 800, y: 700 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 80, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_parking_2', type: 'shadow', position: { x: 1050, y: 260 }, width: 28, height: 36, speed: 1.4, direction: 'down', isActive: true, detectionRadius: 90, patrolPath: [{ x: 1050, y: 180 }, { x: 1050, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 85, stunned: false, stunnedTimer: 0 },
      { id: 'operator_echo', type: 'operator', position: { x: 1150, y: 780 }, width: 30, height: 40, speed: 0.75, direction: 'up', isActive: true, detectionRadius: 160, behaviorState: 'chase', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_parking_3', type: 'shadow', position: { x: 650, y: 360 }, width: 28, height: 36, speed: 1.45, direction: 'right', isActive: true, detectionRadius: 90, patrolPath: [{ x: 420, y: 360 }, { x: 900, y: 360 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 82, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_parking_4', type: 'shadow', position: { x: 250, y: 220 }, width: 28, height: 36, speed: 1.35, direction: 'down', isActive: true, detectionRadius: 86, patrolPath: [{ x: 250, y: 160 }, { x: 250, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 80, stunned: false, stunnedTimer: 0 },
      { id: 'parking_echo_1', type: 'echo', position: { x: 970, y: 640 }, width: 26, height: 34, speed: 1.2, direction: 'left', isActive: true, detectionRadius: 82, patrolPath: [{ x: 760, y: 640 }, { x: 1120, y: 640 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 100, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'keycard_b1', type: 'key', position: { x: 750, y: 150 }, width: 24, height: 16, collected: false, dialogueId: 'keycard_1', hidden: false, inventoryItem: { id: 'keycard_b1', type: 'key', name: 'Tarjeta B1', description: 'Tarjeta de acceso al nivel B1.' } },
      { id: 'buff_l5_sanity', type: 'tool', position: { x: 300, y: 230 }, width: 24, height: 24, collected: false, dialogueId: 'buff_sanity', hidden: false, buff: { sanity: 35 } },
      { id: 'keycard_b2', type: 'key', position: { x: 500, y: 450 }, width: 24, height: 16, collected: false, dialogueId: 'keycard_2', hidden: false, inventoryItem: { id: 'keycard_b2', type: 'key', name: 'Tarjeta B2', description: 'Tarjeta de acceso al nivel B2.' } },
      { id: 'buff_l5_resilience', type: 'tool', position: { x: 720, y: 690 }, width: 24, height: 24, collected: false, dialogueId: 'buff_resilience', hidden: false, buff: { health: 20, sanity: 20, stamina: 35 } },
      { id: 'tape_5', type: 'vhs_tape', position: { x: 900, y: 780 }, width: 24, height: 24, collected: false, dialogueId: 'tape_5', hidden: false },
    ],
    npcs: [
      { id: 'camilo', name: 'Camilo Cifuentes', position: { x: 850, y: 750 }, width: 24, height: 32, dialogueIds: ['camilo_1', 'camilo_2'], currentDialogueIndex: 0, sprite: 'npc_male' },
    ],
    switches: [],
    puzzles: [],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_operator', text: 'El Operador siempre sabe dónde estás. ¡No intentes esconderte, solo corre!', triggerCondition: 'deaths', conditionValue: 2, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 950, y: 780 },
    exitWidth: 50,
    exitHeight: 60,
    exitLocked: false,
    introDialogueIds: ['intro_l5_1', 'intro_l5_2'],
    completionDialogueIds: ['operator_appear', 'complete_5'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 6 - El Hospital Abandonado (Valve/Dial puzzle)
  {
    id: 6,
    name: 'El Hospital Abandonado',
    description: 'Marta Urrutia guarda secretos sobre el Orfeo.',
    objective: 'Encuentra los 3 expedientes medicos para descubrir el codigo de las valvulas (7-3-1). Ajusta las valvulas para abrir el ala psiquiatrica.',
    width: 1200,
    height: 900,
    playerStart: { x: 100, y: 450 },
    backgroundColor: '#15171b',
    ambientColor: '#0c0e12',
    fogOfWar: true,
    visibilityRadius: 165,
    isDark: true,
    lightsOn: false,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1200, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 860 }, width: 1200, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 900, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 1160, y: 0 }, width: 40, height: 900, solid: true },
      // Hospital corridors
      { id: 'corridor_1', type: 'wall', position: { x: 200, y: 40 }, width: 20, height: 300, solid: true },
      { id: 'corridor_2', type: 'wall', position: { x: 200, y: 440 }, width: 20, height: 420, solid: true },
      { id: 'corridor_3', type: 'wall', position: { x: 400, y: 40 }, width: 20, height: 400, solid: true },
      { id: 'corridor_4', type: 'wall', position: { x: 400, y: 540 }, width: 20, height: 320, solid: true },
      { id: 'corridor_5', type: 'wall', position: { x: 600, y: 140 }, width: 20, height: 300, solid: true },
      { id: 'corridor_6', type: 'wall', position: { x: 600, y: 540 }, width: 20, height: 320, solid: true },
      { id: 'corridor_7', type: 'wall', position: { x: 800, y: 40 }, width: 20, height: 350, solid: true },
      { id: 'corridor_8', type: 'wall', position: { x: 800, y: 490 }, width: 20, height: 370, solid: true },
      // Psychiatric wing door
      { id: 'psych_door', type: 'door', position: { x: 1000, y: 400 }, width: 60, height: 100, solid: true, isOpen: false, requiresKey: 'valve_complete' },
      // Beds/furniture
      { id: 'bed_1', type: 'furniture', position: { x: 80, y: 100 }, width: 80, height: 50, solid: true },
      { id: 'bed_2', type: 'furniture', position: { x: 280, y: 200 }, width: 80, height: 50, solid: true },
      { id: 'bed_3', type: 'furniture', position: { x: 500, y: 100 }, width: 80, height: 50, solid: true },
      { id: 'bed_4', type: 'furniture', position: { x: 700, y: 600 }, width: 80, height: 50, solid: true },
    ],
    enemies: [
      { id: 'echo_hospital_1', type: 'echo', position: { x: 300, y: 300 }, width: 26, height: 34, speed: 1.3, direction: 'down', isActive: true, detectionRadius: 100, patrolPath: [{ x: 300, y: 100 }, { x: 300, y: 400 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 100, stunned: false, stunnedTimer: 0 },
      { id: 'echo_hospital_2', type: 'echo', position: { x: 700, y: 250 }, width: 26, height: 34, speed: 1.4, direction: 'left', isActive: true, detectionRadius: 90, patrolPath: [{ x: 500, y: 250 }, { x: 900, y: 250 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 90, stunned: false, stunnedTimer: 0 },
      { id: 'echo_hospital_3', type: 'echo', position: { x: 950, y: 620 }, width: 26, height: 34, speed: 1.15, direction: 'left', isActive: true, detectionRadius: 85, patrolPath: [{ x: 760, y: 620 }, { x: 1080, y: 620 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 95, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_hospital', type: 'shadow', position: { x: 420, y: 520 }, width: 28, height: 36, speed: 1.0, direction: 'down', isActive: true, detectionRadius: 75, patrolPath: [{ x: 420, y: 360 }, { x: 420, y: 700 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'echo_hospital_4', type: 'echo', position: { x: 520, y: 720 }, width: 26, height: 34, speed: 1.25, direction: 'right', isActive: true, detectionRadius: 88, patrolPath: [{ x: 300, y: 720 }, { x: 760, y: 720 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 96, stunned: false, stunnedTimer: 0 },
      { id: 'echo_hospital_5', type: 'echo', position: { x: 1080, y: 360 }, width: 26, height: 34, speed: 1.28, direction: 'down', isActive: true, detectionRadius: 88, patrolPath: [{ x: 1080, y: 180 }, { x: 1080, y: 620 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 100, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_hospital_2', type: 'shadow', position: { x: 780, y: 500 }, width: 28, height: 36, speed: 1.1, direction: 'left', isActive: true, detectionRadius: 78, patrolPath: [{ x: 600, y: 500 }, { x: 980, y: 500 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'shadow_hospital_3', type: 'shadow', position: { x: 180, y: 600 }, width: 28, height: 36, speed: 1.05, direction: 'down', isActive: true, detectionRadius: 76, patrolPath: [{ x: 180, y: 420 }, { x: 180, y: 760 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'record_1', type: 'document', position: { x: 120, y: 200 }, width: 20, height: 24, collected: false, dialogueId: 'medical_record_1', hidden: false },
      { id: 'buff_l6_health', type: 'tool', position: { x: 260, y: 520 }, width: 24, height: 24, collected: false, dialogueId: 'buff_health', hidden: false, buff: { health: 35 } },
      { id: 'record_2', type: 'document', position: { x: 550, y: 600 }, width: 20, height: 24, collected: false, dialogueId: 'medical_record_2', hidden: false },
      { id: 'record_3', type: 'document', position: { x: 900, y: 150 }, width: 20, height: 24, collected: false, dialogueId: 'medical_record_3', hidden: false },
      { id: 'buff_l6_sanity', type: 'tool', position: { x: 760, y: 360 }, width: 24, height: 24, collected: false, dialogueId: 'buff_sanity', hidden: false, buff: { sanity: 30 } },
      { id: 'tape_6', type: 'vhs_tape', position: { x: 1080, y: 450 }, width: 24, height: 24, collected: false, dialogueId: 'tape_6', hidden: false },
      { id: 'memory_fragment_2', type: 'memory_fragment', position: { x: 1080, y: 550 }, width: 24, height: 24, collected: false, dialogueId: 'memory_2', hidden: false },
    ],
    npcs: [
      { id: 'marta', name: 'Marta Urrutia', position: { x: 1080, y: 500 }, width: 24, height: 32, dialogueIds: ['marta_1', 'marta_2'], currentDialogueIndex: 0, sprite: 'npc_female' },
    ],
    switches: [
      { id: 'valve_1', type: 'valve', position: { x: 150, y: 700 }, width: 40, height: 40, isActivated: false, linkedTo: ['psych_door'], dialValue: 0 },
      { id: 'valve_2', type: 'valve', position: { x: 500, y: 750 }, width: 40, height: 40, isActivated: false, linkedTo: ['psych_door'], dialValue: 0 },
      { id: 'valve_3', type: 'valve', position: { x: 850, y: 700 }, width: 40, height: 40, isActivated: false, linkedTo: ['psych_door'], dialValue: 0 },
    ],
    puzzles: [
      {
        id: 'valve_puzzle',
        type: 'code',
        name: 'Valvulas del Ala Psiquiatrica',
        description: 'Ajusta las 3 valvulas a los valores correctos (0-9)',
        hint: 'Los expedientes medicos contienen los numeros...',
        isSolved: false,
        correctCode: '731',
        enteredCode: '',
        unlocksDoor: 'psych_door',
      },
    ],
    pressurePlates: [],
    hazardZones: [
      { id: 'gas_1', type: 'gas', position: { x: 450, y: 350 }, width: 100, height: 100, isActive: true, pattern: 'timed', onDuration: 240, offDuration: 180, currentTimer: 0, damage: 8 },
    ],
    hints: [
      { id: 'hint_valves', text: 'Interactua con las valvulas y usa las teclas de numero para ajustar el valor.', triggerCondition: 'stuck', conditionValue: 45, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 1100, y: 420 },
    exitWidth: 50,
    exitHeight: 80,
    exitLocked: true,
    exitUnlockedBy: 'valve_puzzle',
    introDialogueIds: ['intro_l6_1', 'intro_l6_2'],
    completionDialogueIds: ['complete_6'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 7 - La Estación (Logic puzzle - 5 doors)
  {
    id: 7,
    name: 'La Estación',
    description: 'Gabriel Llorente tiene respuestas sobre Nicolas.',
    objective: 'Descifra las pistas logicas para elegir la puerta correcta. Las puertas incorrectas liberan sombras.',
    width: 1000,
    height: 800,
    playerStart: { x: 500, y: 700 },
    backgroundColor: '#0c0e12',
    ambientColor: '#06070a',
    fogOfWar: false,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1000, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 760 }, width: 1000, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 800, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 960, y: 0 }, width: 40, height: 800, solid: true },
      // Platform with 5 doors
      { id: 'platform', type: 'wall', position: { x: 100, y: 200 }, width: 800, height: 20, solid: true },
      // 5 Doors - only middle one (eye) is correct
      { id: 'door_fire', type: 'door', position: { x: 120, y: 100 }, width: 60, height: 100, solid: true, isOpen: false },
      { id: 'door_water', type: 'door', position: { x: 280, y: 100 }, width: 60, height: 100, solid: true, isOpen: false },
      { id: 'door_eye', type: 'door', position: { x: 440, y: 100 }, width: 60, height: 100, solid: true, isOpen: false }, // CORRECT
      { id: 'door_dark', type: 'door', position: { x: 600, y: 100 }, width: 60, height: 100, solid: true, isOpen: false },
      { id: 'door_light', type: 'door', position: { x: 760, y: 100 }, width: 60, height: 100, solid: true, isOpen: false },
      // Clue boards
      { id: 'board_1', type: 'furniture', position: { x: 150, y: 400 }, width: 100, height: 60, solid: true },
      { id: 'board_2', type: 'furniture', position: { x: 450, y: 500 }, width: 100, height: 60, solid: true },
      { id: 'board_3', type: 'furniture', position: { x: 750, y: 400 }, width: 100, height: 60, solid: true },
    ],
    enemies: [
      { id: 'station_shadow_1', type: 'shadow', position: { x: 220, y: 610 }, width: 26, height: 34, speed: 1.2, direction: 'right', isActive: true, detectionRadius: 75, patrolPath: [{ x: 160, y: 610 }, { x: 380, y: 610 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 70, stunned: false, stunnedTimer: 0 },
      { id: 'station_shadow_2', type: 'shadow', position: { x: 760, y: 610 }, width: 26, height: 34, speed: 1.2, direction: 'left', isActive: true, detectionRadius: 75, patrolPath: [{ x: 620, y: 610 }, { x: 840, y: 610 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 70, stunned: false, stunnedTimer: 0 },
      { id: 'station_shadow_3', type: 'shadow', position: { x: 520, y: 320 }, width: 26, height: 34, speed: 1.28, direction: 'right', isActive: true, detectionRadius: 78, patrolPath: [{ x: 360, y: 320 }, { x: 720, y: 320 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 76, stunned: false, stunnedTimer: 0 },
      { id: 'station_shadow_4', type: 'shadow', position: { x: 860, y: 430 }, width: 26, height: 34, speed: 1.18, direction: 'down', isActive: true, detectionRadius: 74, patrolPath: [{ x: 860, y: 260 }, { x: 860, y: 620 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 72, stunned: false, stunnedTimer: 0 },
      { id: 'station_echo_1', type: 'echo', position: { x: 330, y: 460 }, width: 26, height: 34, speed: 1.1, direction: 'left', isActive: true, detectionRadius: 72, patrolPath: [{ x: 170, y: 460 }, { x: 520, y: 460 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 82, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'clue_logic_1', type: 'document', position: { x: 180, y: 350 }, width: 20, height: 24, collected: false, dialogueId: 'logic_clue_1', hidden: false },
      { id: 'buff_l7_speed', type: 'tool', position: { x: 500, y: 630 }, width: 24, height: 24, collected: false, dialogueId: 'buff_speed', hidden: false, buff: { speed: 0.1, stamina: 30 } },
      { id: 'clue_logic_2', type: 'document', position: { x: 480, y: 450 }, width: 20, height: 24, collected: false, dialogueId: 'logic_clue_2', hidden: false },
      { id: 'clue_logic_3', type: 'document', position: { x: 780, y: 350 }, width: 20, height: 24, collected: false, dialogueId: 'logic_clue_3', hidden: false },
      { id: 'buff_l7_sanity', type: 'tool', position: { x: 840, y: 520 }, width: 24, height: 24, collected: false, dialogueId: 'buff_sanity', hidden: false, buff: { sanity: 25 } },
      { id: 'tape_7', type: 'vhs_tape', position: { x: 460, y: 60 }, width: 24, height: 24, collected: false, dialogueId: 'tape_7', hidden: true, revealedBy: 'logic_puzzle' },
    ],
    npcs: [
      { id: 'gabriel', name: 'Gabriel Llorente', position: { x: 470, y: 60 }, width: 24, height: 32, dialogueIds: ['gabriel_1', 'gabriel_2', 'gabriel_3'], currentDialogueIndex: 0, sprite: 'npc_male' },
    ],
    switches: [],
    puzzles: [
      {
        id: 'logic_puzzle',
        type: 'logic',
        name: 'Las Cinco Puertas',
        description: 'Elige la puerta correcta basándote en las pistas',
        hint: 'FUEGO y AGUA no están juntas. La verdad está entre OSCURIDAD y LUZ. El OJO que todo lo ve está en el centro.',
        isSolved: false,
        logicClues: ['La puerta del fuego no está junto a la del agua.', 'La verdad se encuentra entre la oscuridad y la luz.', 'El ojo que todo lo ve está en el centro.'],
        unlocksDoor: 'door_eye',
        unlocksCollectible: 'tape_7',
        triggersDialogue: 'gabriel_1',
        spawnEnemy: 'shadow_trap',
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_logic', text: 'Las puertas de izquierda a derecha son: FUEGO, AGUA, OJO, OSCURIDAD, LUZ. El OJO está en el centro.', triggerCondition: 'deaths', conditionValue: 3, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 440, y: 50 },
    exitWidth: 60,
    exitHeight: 50,
    exitLocked: true,
    exitUnlockedBy: 'logic_puzzle',
    introDialogueIds: ['intro_l7_1', 'intro_l7_2'],
    completionDialogueIds: ['complete_7'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 8 - Edificio Orfeo Exterior (Stealth challenge)
  {
    id: 8,
    name: 'Edificio Orfeo - Exterior',
    description: 'El lugar donde todo comenzo. El cadaver de concreto y ceniza.',
    objective: 'Infiltrate sin ser detectado. 3 detecciones = Game Over. Encuentra la entrada al sotano. Sprint hace ruido!',
    width: 1200,
    height: 1000,
    playerStart: { x: 100, y: 900 },
    backgroundColor: '#120d10',
    ambientColor: '#080507',
    fogOfWar: true,
    visibilityRadius: 210,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1200, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 960 }, width: 1200, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 1000, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 1160, y: 0 }, width: 40, height: 1000, solid: true },
      // Building exterior
      { id: 'building_wall_1', type: 'wall', position: { x: 400, y: 40 }, width: 400, height: 400, solid: true },
      { id: 'debris_1', type: 'debris', position: { x: 200, y: 300 }, width: 100, height: 80, solid: true },
      { id: 'debris_2', type: 'debris', position: { x: 900, y: 400 }, width: 120, height: 60, solid: true },
      { id: 'debris_3', type: 'debris', position: { x: 600, y: 600 }, width: 80, height: 100, solid: true },
      // Hiding spots
      { id: 'hide_1', type: 'hiding_spot', position: { x: 150, y: 500 }, width: 60, height: 60, solid: true, canHideIn: true },
      { id: 'hide_2', type: 'hiding_spot', position: { x: 350, y: 700 }, width: 60, height: 60, solid: true, canHideIn: true },
      { id: 'hide_3', type: 'hiding_spot', position: { x: 800, y: 600 }, width: 60, height: 60, solid: true, canHideIn: true },
      { id: 'hide_4', type: 'hiding_spot', position: { x: 1000, y: 300 }, width: 60, height: 60, solid: true, canHideIn: true },
      // Basement entrance
      { id: 'basement_door', type: 'door', position: { x: 550, y: 440 }, width: 80, height: 60, solid: false, isOpen: true },
    ],
    enemies: [
      { id: 'stalker_1', type: 'stalker', position: { x: 300, y: 400 }, width: 30, height: 38, speed: 2.0, direction: 'right', isActive: true, detectionRadius: 130, patrolPath: [{ x: 200, y: 400 }, { x: 400, y: 400 }, { x: 400, y: 600 }, { x: 200, y: 600 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 150, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_2', type: 'stalker', position: { x: 900, y: 500 }, width: 30, height: 38, speed: 1.8, direction: 'left', isActive: true, detectionRadius: 120, patrolPath: [{ x: 700, y: 500 }, { x: 1000, y: 500 }, { x: 1000, y: 700 }, { x: 700, y: 700 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 140, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_3', type: 'stalker', position: { x: 600, y: 800 }, width: 30, height: 38, speed: 2.2, direction: 'up', isActive: true, detectionRadius: 110, patrolPath: [{ x: 400, y: 800 }, { x: 800, y: 800 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 130, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_4', type: 'stalker', position: { x: 1050, y: 820 }, width: 30, height: 38, speed: 1.7, direction: 'left', isActive: true, detectionRadius: 105, patrolPath: [{ x: 900, y: 820 }, { x: 1100, y: 820 }, { x: 1100, y: 920 }, { x: 900, y: 920 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 135, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_5', type: 'stalker', position: { x: 520, y: 220 }, width: 30, height: 38, speed: 1.6, direction: 'down', isActive: true, detectionRadius: 100, patrolPath: [{ x: 520, y: 180 }, { x: 700, y: 180 }, { x: 700, y: 340 }, { x: 520, y: 340 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 125, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_6', type: 'stalker', position: { x: 180, y: 760 }, width: 30, height: 38, speed: 1.9, direction: 'right', isActive: true, detectionRadius: 115, patrolPath: [{ x: 120, y: 760 }, { x: 420, y: 760 }, { x: 420, y: 900 }, { x: 120, y: 900 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 145, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_7', type: 'stalker', position: { x: 980, y: 220 }, width: 30, height: 38, speed: 1.85, direction: 'down', isActive: true, detectionRadius: 115, patrolPath: [{ x: 880, y: 220 }, { x: 1100, y: 220 }, { x: 1100, y: 430 }, { x: 880, y: 430 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 140, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_8', type: 'stalker', position: { x: 260, y: 260 }, width: 30, height: 38, speed: 1.75, direction: 'down', isActive: true, detectionRadius: 105, patrolPath: [{ x: 180, y: 260 }, { x: 360, y: 260 }, { x: 360, y: 520 }, { x: 180, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 130, stunned: false, stunnedTimer: 0 },
      { id: 'stalker_9', type: 'stalker', position: { x: 740, y: 900 }, width: 30, height: 38, speed: 1.7, direction: 'left', isActive: true, detectionRadius: 105, patrolPath: [{ x: 560, y: 900 }, { x: 920, y: 900 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 125, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'buff_l8_stamina', type: 'tool', position: { x: 350, y: 740 }, width: 24, height: 24, collected: false, dialogueId: 'buff_stamina', hidden: false, buff: { stamina: 60 } },
      { id: 'tape_8', type: 'vhs_tape', position: { x: 580, y: 480 }, width: 24, height: 24, collected: false, dialogueId: 'tape_8', hidden: false },
      { id: 'buff_l8_resilience', type: 'tool', position: { x: 960, y: 620 }, width: 24, height: 24, collected: false, dialogueId: 'buff_resilience', hidden: false, buff: { health: 25, sanity: 25, stamina: 25 } },
      { id: 'memory_fragment_3', type: 'memory_fragment', position: { x: 1050, y: 200 }, width: 24, height: 24, collected: false, dialogueId: 'memory_3', hidden: false },
    ],
    npcs: [],
    switches: [],
    puzzles: [
      {
        id: 'stealth_challenge',
        type: 'stealth',
        name: 'Infiltracion',
        description: 'Llega al sotano sin ser detectado 3 veces',
        hint: 'Usa los escondites (Shift). No corras (Sprint hace ruido). Los enemigos tienen patrones de patrulla.',
        isSolved: false,
        unlocksExit: true,
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [
      { id: 'hint_stealth_2', text: 'Los enemigos escuchan tus pasos si corres. Camina lento y usa las sombras.', triggerCondition: 'deaths', conditionValue: 1, hasBeenShown: false },
    ],
    hidingSpots: [{ x: 150, y: 500 }, { x: 350, y: 700 }, { x: 800, y: 600 }, { x: 1000, y: 300 }],
    exitPosition: { x: 560, y: 450 },
    exitWidth: 60,
    exitHeight: 50,
    exitLocked: false,
    introDialogueIds: ['intro_l8_1', 'intro_l8_2', 'stealth_tip'],
    completionDialogueIds: ['basement_found', 'complete_8'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 9 - Edificio Orfeo Interior (Memory sequence puzzle)
  {
    id: 9,
    name: 'Edificio Orfeo - Interior',
    description: 'El interior guarda los ecos de esa noche. Las paredes recuerdan.',
    objective: 'Activa las 5 estaciones de memoria en el ORDEN CRONOLÓGICO correcto para desbloquear el piso 7.',
    width: 1000,
    height: 1000,
    playerStart: { x: 500, y: 900 },
    backgroundColor: '#13090b',
    ambientColor: '#090405',
    fogOfWar: true,
    visibilityRadius: 185,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 1000, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 960 }, width: 1000, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 1000, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 960, y: 0 }, width: 40, height: 1000, solid: true },
      // Burnt corridors
      { id: 'burnt_wall_1', type: 'debris', position: { x: 200, y: 200 }, width: 150, height: 100, solid: true },
      { id: 'burnt_wall_2', type: 'debris', position: { x: 650, y: 300 }, width: 100, height: 150, solid: true },
      { id: 'burnt_wall_3', type: 'debris', position: { x: 300, y: 500 }, width: 120, height: 80, solid: true },
      { id: 'burnt_wall_4', type: 'debris', position: { x: 700, y: 600 }, width: 80, height: 120, solid: true },
      // Final door to floor 7
      { id: 'floor7_door', type: 'door', position: { x: 450, y: 60 }, width: 100, height: 80, solid: true, isOpen: false, requiresKey: 'memory_complete' },
    ],
    enemies: [
      { id: 'operator_orfeo', type: 'operator', position: { x: 800, y: 800 }, width: 34, height: 44, speed: 1.0, direction: 'up', isActive: true, detectionRadius: 250, behaviorState: 'chase', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_echo_1', type: 'echo', position: { x: 260, y: 360 }, width: 26, height: 34, speed: 1.2, direction: 'right', isActive: true, detectionRadius: 90, patrolPath: [{ x: 160, y: 360 }, { x: 440, y: 360 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 90, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_shadow_1', type: 'shadow', position: { x: 760, y: 560 }, width: 28, height: 36, speed: 1.1, direction: 'down', isActive: true, detectionRadius: 85, patrolPath: [{ x: 760, y: 420 }, { x: 760, y: 760 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_echo_2', type: 'echo', position: { x: 460, y: 260 }, width: 26, height: 34, speed: 1.22, direction: 'down', isActive: true, detectionRadius: 90, patrolPath: [{ x: 460, y: 120 }, { x: 460, y: 520 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 92, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_echo_3', type: 'echo', position: { x: 620, y: 820 }, width: 26, height: 34, speed: 1.18, direction: 'left', isActive: true, detectionRadius: 88, patrolPath: [{ x: 360, y: 820 }, { x: 860, y: 820 }], patrolIndex: 0, behaviorState: 'patrol', canHear: true, hearingRadius: 90, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_shadow_2', type: 'shadow', position: { x: 180, y: 660 }, width: 28, height: 36, speed: 1.15, direction: 'right', isActive: true, detectionRadius: 86, patrolPath: [{ x: 120, y: 660 }, { x: 420, y: 660 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'orfeo_shadow_3', type: 'shadow', position: { x: 860, y: 280 }, width: 28, height: 36, speed: 1.1, direction: 'down', isActive: true, detectionRadius: 84, patrolPath: [{ x: 860, y: 160 }, { x: 860, y: 500 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'buff_l9_resilience', type: 'tool', position: { x: 520, y: 620 }, width: 24, height: 24, collected: false, dialogueId: 'buff_resilience', hidden: false, buff: { health: 30, sanity: 30, stamina: 35 } },
      { id: 'buff_l9_speed', type: 'tool', position: { x: 820, y: 300 }, width: 24, height: 24, collected: false, dialogueId: 'buff_speed', hidden: false, buff: { speed: 0.1, stamina: 20 } },
      { id: 'tape_9', type: 'vhs_tape', position: { x: 500, y: 100 }, width: 24, height: 24, collected: false, dialogueId: 'tape_9', hidden: true, revealedBy: 'memory_puzzle' },
    ],
    npcs: [
      { id: 'nicolas_echo', name: 'Nicolas (Eco)', position: { x: 500, y: 80 }, width: 24, height: 32, dialogueIds: ['nicolas_1', 'nicolas_2', 'nicolas_3'], currentDialogueIndex: 0, sprite: 'npc_child' },
    ],
    switches: [
      { id: 'memory_1', type: 'button', position: { x: 150, y: 300 }, width: 50, height: 50, isActivated: false, linkedTo: [], correctSequenceIndex: 0 },
      { id: 'memory_2', type: 'button', position: { x: 800, y: 200 }, width: 50, height: 50, isActivated: false, linkedTo: [], correctSequenceIndex: 1 },
      { id: 'memory_3', type: 'button', position: { x: 500, y: 450 }, width: 50, height: 50, isActivated: false, linkedTo: [], correctSequenceIndex: 2 },
      { id: 'memory_4', type: 'button', position: { x: 200, y: 700 }, width: 50, height: 50, isActivated: false, linkedTo: [], correctSequenceIndex: 3 },
      { id: 'memory_5', type: 'button', position: { x: 750, y: 750 }, width: 50, height: 50, isActivated: false, linkedTo: [], correctSequenceIndex: 4 },
    ],
    puzzles: [
      {
        id: 'memory_puzzle',
        type: 'memory',
        name: 'Reconstruccion de Memoria',
        description: 'Activa las estaciones en el orden en que sucedieron los eventos',
        hint: 'Orden: 1. Jugaban 2. Humo 3. Corrieron 4. Derrumbe 5. Soltó la mano',
        isSolved: false,
        memorySequence: ['memory_1', 'memory_2', 'memory_3', 'memory_4', 'memory_5'],
        playerSequence: [],
        unlocksDoor: 'floor7_door',
        unlocksCollectible: 'tape_9',
      },
    ],
    pressurePlates: [],
    hazardZones: [
      { id: 'fire_1', type: 'fire', position: { x: 100, y: 500 }, width: 80, height: 80, isActive: true, pattern: 'always', damage: 12 },
      { id: 'fire_2', type: 'fire', position: { x: 400, y: 650 }, width: 100, height: 60, isActive: true, pattern: 'always', damage: 12 },
      { id: 'fire_3', type: 'fire', position: { x: 850, y: 400 }, width: 70, height: 90, isActive: true, pattern: 'always', damage: 12 },
    ],
    hints: [
      { id: 'hint_memory', text: 'Los eventos en orden: Jugaban en el pasillo > Humo subió > Corrieron a la salida > Pasillo se derrumbó > Soltó la mano.', triggerCondition: 'deaths', conditionValue: 2, hasBeenShown: false },
    ],
    hidingSpots: [],
    exitPosition: { x: 460, y: 70 },
    exitWidth: 80,
    exitHeight: 70,
    exitLocked: true,
    exitUnlockedBy: 'memory_puzzle',
    introDialogueIds: ['intro_l9_1', 'intro_l9_2'],
    completionDialogueIds: ['complete_9'],
    requiredTapes: 1,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
  // Level 10 - La Verdad Final (Dialogue puzzle - answer correctly)
  {
    id: 10,
    name: 'La Verdad Final',
    description: 'Confronta al Operador. Confronta tu verdad.',
    objective: 'Responde las preguntas del Operador con HONESTIDAD. Las respuestas incorrectas reducen tu cordura. Si llegas a 0, el ciclo se repite.',
    width: 600,
    height: 600,
    playerStart: { x: 300, y: 500 },
    backgroundColor: '#000000',
    ambientColor: '#050000',
    fogOfWar: false,
    obstacles: [
      { id: 'wall_top', type: 'wall', position: { x: 0, y: 0 }, width: 600, height: 40, solid: true },
      { id: 'wall_bottom', type: 'wall', position: { x: 0, y: 560 }, width: 600, height: 40, solid: true },
      { id: 'wall_left', type: 'wall', position: { x: 0, y: 0 }, width: 40, height: 600, solid: true },
      { id: 'wall_right', type: 'wall', position: { x: 560, y: 0 }, width: 40, height: 600, solid: true },
    ],
    enemies: [
      { id: 'operator_final', type: 'operator', position: { x: 280, y: 150 }, width: 40, height: 50, speed: 0, direction: 'down', isActive: true, detectionRadius: 300, behaviorState: 'idle', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'truth_shadow_left', type: 'shadow', position: { x: 120, y: 330 }, width: 26, height: 34, speed: 0.8, direction: 'right', isActive: true, detectionRadius: 65, patrolPath: [{ x: 100, y: 330 }, { x: 240, y: 330 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'truth_shadow_right', type: 'shadow', position: { x: 450, y: 330 }, width: 26, height: 34, speed: 0.8, direction: 'left', isActive: true, detectionRadius: 65, patrolPath: [{ x: 360, y: 330 }, { x: 500, y: 330 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'truth_shadow_top', type: 'shadow', position: { x: 170, y: 230 }, width: 26, height: 34, speed: 0.78, direction: 'right', isActive: true, detectionRadius: 62, patrolPath: [{ x: 120, y: 230 }, { x: 480, y: 230 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'truth_shadow_bottom', type: 'shadow', position: { x: 430, y: 450 }, width: 26, height: 34, speed: 0.82, direction: 'left', isActive: true, detectionRadius: 64, patrolPath: [{ x: 120, y: 450 }, { x: 480, y: 450 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
      { id: 'truth_echo_memory', type: 'echo', position: { x: 300, y: 355 }, width: 24, height: 32, speed: 0.72, direction: 'down', isActive: true, detectionRadius: 58, patrolPath: [{ x: 300, y: 280 }, { x: 300, y: 500 }], patrolIndex: 0, behaviorState: 'patrol', canHear: false, hearingRadius: 0, stunned: false, stunnedTimer: 0 },
    ],
    collectibles: [
      { id: 'buff_l10_truth', type: 'tool', position: { x: 300, y: 420 }, width: 24, height: 24, collected: false, dialogueId: 'buff_resilience', hidden: false, buff: { health: 35, sanity: 45, stamina: 50 } },
      { id: 'buff_l10_sanity', type: 'tool', position: { x: 300, y: 260 }, width: 24, height: 24, collected: false, dialogueId: 'buff_sanity', hidden: false, buff: { sanity: 35 } },
    ],
    npcs: [
      { id: 'nicolas_final', name: 'Nicolas', position: { x: 200, y: 100 }, width: 24, height: 32, dialogueIds: ['nicolas_final'], currentDialogueIndex: 0, sprite: 'npc_child' },
      { id: 'gabriel_final', name: 'Gabriel Llorente', position: { x: 400, y: 100 }, width: 24, height: 32, dialogueIds: ['gabriel_final'], currentDialogueIndex: 0, sprite: 'npc_male' },
    ],
    switches: [],
    puzzles: [
      {
        id: 'truth_puzzle',
        type: 'logic',
        name: 'La Verdad',
        description: 'Responde con honestidad',
        hint: 'Solo la verdad puede romper el ciclo.',
        isSolved: false,
        unlocksExit: true,
      },
    ],
    pressurePlates: [],
    hazardZones: [],
    hints: [],
    hidingSpots: [],
    exitPosition: { x: 260, y: 60 },
    exitWidth: 80,
    exitHeight: 60,
    exitLocked: true,
    exitUnlockedBy: 'truth_puzzle',
    introDialogueIds: ['intro_l10_1', 'intro_l10_2'],
    completionDialogueIds: ['ending'],
    requiredTapes: 0,
    isCompleted: false,
    deathCount: 0,
    timeSpent: 0,
  },
]
